### ISSUE TITLE
Customisable Controls

### ISSUE THREAD

**Issue by creepyLANguy** [creepyLANguy/SoundSwitcher#55]
Add Controls submenu. 
- Left Click
- Middle Click

Each offers ffg selections: 
- Switch next device
- Refresh
- Toggle Mode
- Volume Mixer
- Manage Devices

Make sure settings are defaulted in config and persist in config on selection.

**Comment by DerekGooding** [comment]
I don't recommend using the "good first issue" tag on a public project unless you're looking for contributors.

**Comment by creepyLANguy** [comment]
@DerekGooding good point. Removed the tag. Thanks :)
